### ISSUE TITLE
Bug: is() using CSS selector behaves like has()

### ISSUE THREAD

**Issue by jlgrall** [ThomasWeinert/FluentDOM#75]
Result of [FluentDOM\Query->is()](https://github.com/FluentDOM/FluentDOM/wiki/Query-Is):
```PHP
\FluentDOM::QueryCss('<div><span></span></div>', 'html-fragment')->is('span');
// => 1 (true)
```
But it should return false like [jQuery.is()](https://api.jquery.com/is/):
```JavaScript
jQuery('<div><span></span></div>').is('span');
// => false
```

Using:
- PHP 7.0
- fluentdom/fluentdom: 7.0.0
- fluentdom/selectors-phpcss: 1.1.0

Maybe this is a CSS to Xpath translation bug ?

**Comment by jlgrall** [comment]
It is not a CSS to Xpath translation bug. I checked the translation from CSS to Xpath with the underlying library [PhpCss](https://github.com/ThomasWeinert/PhpCss):
```PHP
echo PhpCss::toXpath('div');
// => './/*[local-name() = "div"]'
```
This is correct, but note that it also matches descendant divs (as it should).

The problem seems to be that the results of the xpath evaluation is not checked to contain the current element. So if any descendant matches, it returns a not-empty result, which is interpreted as a match. See: [`Nodes->matches()`](https://github.com/FluentDOM/FluentDOM/blob/fda8452ef698d1ae644d3938513b33d9c3d86eb7/src/FluentDOM/Nodes.php#L444) called from [`Query->is()`](https://github.com/FluentDOM/FluentDOM/blob/fda8452ef698d1ae644d3938513b33d9c3d86eb7/src/FluentDOM/Query.php#L494).

**Comment by ThomasWeinert** [comment]
Thanks for the input and help tracking that problem down.

Actually (in this case) `div` is transformed to `descendant-or-self::*[local-name() = "span"]` so that is affects the current node as well. 

You could check that with:

`echo PhpCss::toXpath('div', \PhpCss\Ass\Vistor\Xpath::OPTION_USE_CONTEXT_SELF);`

To limit it to the current context we would need just `self::*[local-name() = "span"]`. That means a new option is needed in PhpCss.

**Comment by ThomasWeinert** [comment]
I implemented the new context option in PhpCSS and fixed the integration. Here is a test generated from the reported example to validate it.

https://github.com/ThomasWeinert/FluentDOM-Selectors-PHPCss/blob/master/tests/Issues/Issue1Test.php

**Comment by jlgrall** [comment]
Yep, works well with latest version. Great !
