### ISSUE TITLE
Load an HTML fragment from an HTML5 source

### ISSUE THREAD

**Issue by jlgrall** [ThomasWeinert/FluentDOM#76]
When loading, only 1 loader is chosen, so when we set the `$contentType`, it can either be `'html-fragment'` or `'text/html5'` (from plugin loader: [FluentDOM-HTML5](https://github.com/FluentDOM/HTML5)).

Example:
```PHP
// Either:
\FluentDOM::QueryCss($html, 'html-fragment');
// or:
\FluentDOM::QueryCss($html, 'text/html5');
```

So how can I load a html fragment that comes from a HTML5 document ?

To me, 'html-fragment' is not really a content type. It should be a distinct option of the loader.

**Comment by bluehaoran** [comment]
I'd like to bump this issue.

Is there an answer, or perhaps a workaround to make this work? If I wanted to add code to do this, would I do it here, or in the HTML5 repo?

**Comment by ThomasWeinert** [comment]
You can use an option actually:

\FluentDOM::QueryCss($html, 'html', [\FluentDOM\Loader\Html::IS_FRAGMENT => TRUE]);

However it would need to be implemented into the HTML5 loader at: https://github.com/ThomasWeinert/FluentDOM-HTML5
