### ISSUE TITLE
Loading HTML5 fragment bug

### ISSUE THREAD

**Issue by jlgrall** [ThomasWeinert/FluentDOM#79]
With the recent updates to [FluentDOM-HTML5](https://github.com/ThomasWeinert/FluentDOM-HTML5), and with your tip from: #76, I tried to load an HTML5 fragment directly into FluentDOM. But there seems to be something amiss.

```PHP
$src = '<div id="a"><span id="b"></span></div>';
\FluentDOM::QueryCss($src, 'html5', [\FluentDOM\Loader\Html::IS_FRAGMENT => TRUE])->is('div');
// => false
// But it should return true, like:
\FluentDOM::QueryCss($src, 'html-fragment')->is('div');
// => true
```

Using:
- PHP 7.1
- [fluentdom/fluentdom](https://github.com/ThomasWeinert/FluentDOM): 7.0.0
- [fluentdom/html5](https://github.com/ThomasWeinert/FluentDOM-HTML5): 1.5.1
- [fluentdom/selectors-phpcss](https://github.com/ThomasWeinert/FluentDOM-Selectors-PHPCss): 1.2.0

**Comment by ThomasWeinert** [comment]
The HTML5 library does create XHTML by default - including the namespace. You can disable it using an option.

```
$html5 = '<div id="a"><span id="b"></span></div>';
var_dump(
  \FluentDOM::QueryCSS(
    $html5,
    'html5',
    [
      \FluentDOM\HTML5\Loader::IS_FRAGMENT => TRUE,
      \FluentDOM\HTML5\Loader::DISABLE_HTML_NAMESPACE => TRUE
    ]
  )->is('div')
);
```

Or you use a the universal selector:

```
$html5 = '<div id="a"><span id="b"></span></div>';
var_dump(
  \FluentDOM::QueryCSS(
    $html5,
    'html5',
    [
      \FluentDOM\HTML5\Loader::IS_FRAGMENT => TRUE
    ]
  )->is('*|div')
);
```

The loader registers the prefix `html` automatically so you can use it as well (Here was a bug https://github.com/ThomasWeinert/FluentDOM-HTML5/issues/3):

```
$html5 = '<div id="a"><span id="b"></span></div>';
var_dump(
  \FluentDOM::QueryCSS(
    $html5,
    'html5',
    [
      \FluentDOM\HTML5\Loader::IS_FRAGMENT => TRUE
    ]
  )->is('html|div')
);
```
