### ISSUE TITLE
preserveWhitespace in Libxml-Loader

### ISSUE THREAD

**Issue by burki** [ThomasWeinert/FluentDOM#86]
Currently `$document->preserveWhiteSpace` is forced to FALSE

https://github.com/ThomasWeinert/FluentDOM/blob/1620d3834bae86673f1a2cc06dca1c24604e3011/src/FluentDOM/Loader/Supports/Libxml.php#L54

To set this to true, I had to register a new loader that overrides this method.

Would it make sense to introduce something like

    Options::PRESERVE_WHITESPACE => TRUE

that could be passed to the loader to make this behaviour configurable? If you feel comfortable with such an extension, I'd happy to try to come up with a pull request implementing this.

**Comment by ThomasWeinert** [comment]
Implemented it. Please test and confirm. :-)

**Comment by burki** [comment]
I switched to the new option and it behaves exactly as expected. Thanks very much not only for adding this so quickly, but also for the rest of your library which makes XML-handling in PHP so much easier.

**Comment by ThomasWeinert** [comment]
You're welcome. If you have other suggestions please drop me a note/open an issue. 

Released 7.3 with the new feature.
