### ISSUE TITLE
Please support unwrap()

### ISSUE THREAD

**Issue by bkonia** [ThomasWeinert/FluentDOM#87]
Could you please add support for unwrap()?  I just had to do a crazy complicated workaround to unwrap an element.

**Comment by ThomasWeinert** [comment]
Try it out: https://github.com/ThomasWeinert/FluentDOM/commit/bea0a1eba49d319b17455a5906a39ede78be6181

**Comment by bkonia** [comment]
Thanks for doing this, but I can't seem to get it to work. It crashes with the following error:

[18-Aug-2019 20:24:04 UTC] PHP Fatal error:  Uncaught Error: Function name must be a string in /usr/local/lsws/sites/prescientrading.com/vendor/fluentdom/fluentdom/src/FluentDOM/Query.php:424

**Comment by ThomasWeinert** [comment]
Did you try the latest version on master?  This crash on my first commit without a selector. Otherwise can you provide me with an example please?

**Comment by bkonia** [comment]
It works now, thank you!
