### ISSUE TITLE
How to Iterate?

### ISSUE THREAD

**Issue by bkonia** [ThomasWeinert/FluentDOM#88]
I want to iterate through a document using `QueryCSS()` and replace all H2 tags with H4 tags, while retaining the original content for each tag. I tried this:
```
$html->find("h2")->each(function($node, $index) {
     $node->replaceWith("<h4>" . $node->text() . "</h4>");
});
```

but it throws an error, *text() method doesn't exist*, because apparently `each()` returns a list of the text content of the nodes, not the nodes themselves. So then I tried this:

```
$html->find("h2")->each(function($node, $index) {
     $node->replaceWith("<h4>" . $node . "</h4>");
});
```
This performed the replacement, but since `$node` refers to the node text content, it escaped the HTML, so it outputted the raw HTML. How can I get this to work?

**Comment by ThomasWeinert** [comment]
The `$node` argument in the `each()` callback is a DOM node, not a `FluentDOM\Query` instance. You could use the `FluentDOM()` function to wrap it. However it is not really necessary. 

```php
$htmlString = <<<'HTML'
<!DOCTYPE html>
<html><body><h2>ONE<span>TWO</span></h2></body></html>
HTML;

$html = FluentDOM($htmlString, 'html');
$html
  ->find("//h2")
  ->each(
    static function(\FluentDOM\DOM\Element $node)  {
      $newNode = $node->ownerDocument->createElement('h4');
      $newNode->textContent = $node->textContent;
      $node->replaceWith($newNode);
     }
   );

echo $html; 
```

You could even keep the descendant structure:

```php
$html = FluentDOM($htmlString, 'html');
$html
  ->find("//h2")
  ->each(
    static function(\FluentDOM\DOM\Element $node)  {
      $newNode = $node->ownerDocument->createElement('h4');
      $newNode->append($node->childNodes);
      $node->replaceWith($newNode);
     }
   );
```

Or with just DOM objects:

```php
$html = FluentDOM::load($htmlString, 'html');
/** @var \FluentDOM\DOM\Element $node */
foreach ($html("//h2") as $node) {
  $newNode = $node->ownerDocument->createElement('h4');
  $newNode->append($node->childNodes);
  $node->replaceWith($newNode);
}

echo $html;
```

**Comment by bkonia** [comment]
Thank you for the explanation!
