### ISSUE TITLE
What is the correct way to replace elements in a foreach?

### ISSUE THREAD

**Issue by SeriousKen** [ThomasWeinert/FluentDOM#91]
I'm trying to replace elements found with new generated content. I have tried the following where `$query` is a `FluentDOM\Query` object:

``` php
foreach ($query->find('//component') as $element) {
    // Do some stuff to generate HTML string an store in $content
    $content = getComponentHTML($element);
    $element->replaceWith($content);
}
```

But it seems the HTML in `$content` ends up being escaped. This isn't the case if I do something like:

``` php
$query->find('//component')->replaceWith('<h2>Component</h2>');
```

But this doesn't allow any way to generate a replacement for each component element found. What am I missing?

**Comment by ThomasWeinert** [comment]
Try debugging $content (`var_dump($content);`). If it is a valid fragment string it should work.
