### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by iotch** [ThomasWeinert/FluentDOM#92]
Hello. Thanks for the great library! Is there any chances that it will be compatible with PHP8?

**Comment by ThomasWeinert** [comment]
Sorry that I took so long, but the current master branch now works with PHP 8. You can check it out.

I still want to fix all the inspections (return values, ...) before creating a new release.

**Comment by ThomasWeinert** [comment]
Works on PHP 8.0 and 8.1, set up GitHub actions for testing.
